### ISSUE TITLE
Unity Test Task does not finish

### ISSUE THREAD

**Issue by Syntax134** [Dinomite-Studios/unity-azure-pipelines-tasks#136] opened 2020-05-25 08:47 UTC
Hi,

When executing the Unity Test Task, it runs in a timeout everytime. Obviously, no error occurs in the logs (please see attached file). Unity version is 2019.3.8f1, the pipeline runs on a self-hosted agent. Any idea where I could start to investigate?

[UnityTestTask.txt](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/files/4676211/UnityTestTask.txt)

**Comment by ericallam** [comment] 2020-07-09 18:08
We're running into the same issue, 2019.4.1f1, running on a macOS self-hosted agent. Our logs look pretty much identical to @Syntax134's provided above.

**Comment by mpah** [comment] 2020-07-22 10:43
Same result here. @ericallam @Syntax134 did you guys figure out what was causing it or any workaround?

**Comment by ericallam** [comment] 2020-07-22 10:47
Couldn't figure it out so just wrote it manually as a script task

**Comment by Wiktoryn** [comment] 2020-07-30 12:32
I've made a push request with a proposed solution.
The issue is unity runner awaits for the process to exit and for the log file to be present.
During Test task, the Unity process exists ok, but it is not configured to produce any logs, making the task wait endlessly.
The change is to add -logFile argument to Unity process at all times, just as other tasks (Build and Activation).

**Comment by mpah** [comment] 2020-08-04 12:30
@ericallam we ended up doing the same and it worked out, thanks

**Comment by ikriz** [comment] 2020-08-11 21:15
having this same issue it seems the pull request is merged only the task it self hasn't been updated yet on the azure side

**Comment by FejZa** [comment] 2020-08-12 12:57
@ikriz it's published in the marketplace now. Make sure your organization has updated to v2.7.2 of the extension.

**Comment by ikriz** [comment] 2021-04-21 09:45
This issue has resurfaced in the latest push

**Comment by FejZa** [comment] 2021-04-21 09:56
Thanks @ikriz, looking into it.

**Comment by ikriz** [comment] 2021-04-21 11:40
@FejZa heres our log output.. you can see by the timestamps that the timeout of 1 hour is hit. https://gist.github.com/ikriz/6e5964d82a76f87ad690c9acb607096a

**Comment by FejZa** [comment] 2021-04-23 07:28
Thanks everyone. A new fix has been released. Please make sure to update your extension to 2.8.5.

Please note there is a new input variable for the Test Task:

`failOnTestFail`: It defaults to `true` and will make the pipeline fail if any of the tests fail. Set it to `false` to have the pipeline continue with subsequent tasks even if tests failed.

You can then use the new output variable `testsFailed` to know in subsequent tasks whether any tests have failed and decide what to do e.g.

I will close this issue, feel free to reopen in case you run into issues.

**Closed by FejZa** 2021-04-23 07:28 UTC
