### ISSUE TITLE
Hosted Azure DevOps fails to find unity-get-project-version.js

### ISSUE THREAD

**Issue by milsoft** [Dinomite-Studios/unity-azure-pipelines-tasks#54] opened 2019-03-14 19:14 UTC
I know in #49 You mentioned renaming the .ts to .js which would be fine if we were running Azure DevOps server, but we are running the cloud version, so it depends on the published version of your task. It fails to find the .js since it is a .ts, and since it is a task which is downloaded on the fly there is no way for me to change it. Also my attempt is on a Hosted macOS pool.

**Comment by FejZa** [comment] 2019-03-19 06:31
Hey there, sorry I am on vacation and rarely have access to a PC. So you've got that wrong. In #49 I did not say to rename .ts to .js but to NOT rename it. The .ts files are TypeScript files, they can't just be renamed to JavaScript files.

So to find the root of this issue I need to how how you installed the tasks? Did you get them from the marketplace and installed them to your organization or did you upload them yourself using TSX commnad line?

I am using hosted agents myself and never stumbled upon this issue so there must be something else causing it. Pretty sure we can figure it out.

**Comment by Nirmalendu** [comment] 2019-03-19 11:57
Hi, I am facing a similar issue.
Steps to reproduce:
* Install the extension from the marketplace
* Create a build pipeline using `hosted agent`
* Add `Unity Get Project Version` 
* Add `Unity Build task`
* Save, queue and build

The error I get is
```log
##[section]Starting: Unity Get Project Version
==============================================================================
Task         : Unity Get Project Version
Description  : Gets the project version of a Unity project.
Version      : 1.0.0
Author       : Dinomite Studios
Help         : Gets the project version of a Unity project. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[error]File not found: 'D:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.0\unity-get-project-version.js'
##[section]Finishing: Unity Get Project Version
```

Additionally, during the build it looks like the hosted agent cannot find the Unity Editor from the Hub directory (I am trying to build a standalone build for Windows)
```log
##[section]Starting: Unity Build for project_name
==============================================================================
Task         : Unity Build
Description  : Build a Unity project and get the exported output files.
Version      : 2.3.0
Author       : Dinomite Studios
Help         : Builds a Unity project to supported build target platforms. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[error]Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2018.2.17f1\Editor
##[section]Finishing: Unity Build for project_name
```

**Comment by milsoft** [comment] 2019-03-19 12:40
I got it from the marketplace. I had considered running the marketplace version on a local machine so that I could see what the structure looks like. Another think is that I can’t find unity listed as a capability anywhere for the truly hosted agents. 

In the mean time I have compiled it myself with tsc and tfx and uploaded it. It seems to be working just fine that way. Is there a possibility that an uncompiled version got pushed to the marketplace?

Thanks for all the help

**Comment by Nirmalendu** [comment] 2019-03-19 13:10
@milsoft Can you please help me with the steps you followed?

**Comment by FejZa** [comment] 2019-03-19 13:32
Hi @Nirmalendu @milsoft,

thank you for the reports. I'll  make sure to do some more research on what is causing this issue. It's not possible to release the uncompiled TypeScript to marketplace. Also I am using the marketeplace install myself. So unfortunately that seems not to be the issue here.

Sadly I still haven't found the time to properly update the documentation for hosted agents. If you want to use a hosted agent, you need to make sure the proper Unity Editor gets installed before building the project. Your pipeline needs to look e.g. like this (for standalone build):

![Standalone Pipeline](https://i.ibb.co/0Mq3KhT/pipeline-hosted-standalone.png)

### Unity Get Project Version
This task will determine the needed Unity editor version from the project. (Note that you only need this task when using a hosted agent and installing the Unity editor before building, the Unity Build task can be used on it's own on custom agents because it can find the needed editor as well).

### Install UnitySetup.Powershell module
Add this PowerShell task and configure it to inline script, then add the following script:
`Install-Module -Name UnitySetup -AllowPrerelease -RequiredVersion 5.0.107-develop -Scope CurrentUser -Repository PSGallery -Force`

This will install the required PowerShell module to install Unity versions on the fly.

### Install Unity Editor
Another inline PowerShell script task here. Please paste the following script:
`Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version '$(unitygetprojectversion.projectVersion)' -Components Windows,Windows_IL2CPP,UWP_IL2CPP,WebGL) -Verbose`

Please not that I am using the `$(unitygetprojectversion.projectVersion)` output variable from the Unity Get Project Version task here. Make sure you set the reference name right here.

### Unity Activate License
Building on hosted agents unfortunately requires the Unity editor to be actiavtes with a license. Otherweise because it is newly installed it will fail to build since there is no logged in user. On custom agents you can login a free license user as well. The used license will get released once the build has finished automatically.

### Unity Build standalone
Now this is the actuayl Unity Built task that will build the project.

### Publish Artifact: Build Output
This is just an example publishing the build output. You could as well proceed and do whatever you require with the build output.

Please let me know if you need further help here.

**Comment by milsoft** [comment] 2019-03-19 16:18
@Nirmalendu @FejZa 

Here are the steps I followed, maybe it can be of help to someone or everyone.

1. First you need to clone the repo and go into it

git clone https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks.git
cd unity-azure-pipelines-tasks/

2. Then you need to make sure you have npm and all the node packages required by Microsoft and also the extension

npm install -g npm
npm install azure-pipelines-task-lib
npm install -g tfx-cli
npm install @types/node --save-dev
npm install @types/q --save-dev
npm install -g typescript
npm install -g fs-extra
npm install -g find-process

3. Now you need to initialize the folder as a TypeScript target
tsc --init

4. You will need to change some version thing (can't remember) to a newer version according to the Microsoft docs

vim tsconfig.json

5. Then you essentially need to go into each Task's folder (and each version) and install the fs-extra package. I installed it globally above but tsc was still throwing an error.

cd Tasks/
cd UnityActivateLicense/
cd UnityActivateLicenseV1/
npm install fs-extra
tsc

(Go back to project root)

cd UnityBuild/
cd UnityBuildV1
npm install fs-extra
tsc

cd ..
cd UnityBuildV2
npm install fs-extra
tsc

(Go back to project root)

cd UnityGetProjectVersion/
cd UnityGetProjectVersionV1/
npm install fs-extra
tsc

(Go back to project root)

6. Now you need to modify the vss-extension.json to be your own publisher and version, make sure it's private (out of respect for the developer) and change "Categories" to be "Azure Pipelines" as the "Build Plans" or whatever target is no longer valid

vim vss-extension.json

7. Next create the extension binary from the modified json

tfx extension create --manifest-globs vss-extension.json

8. Finally you can upload the extension to your marketplace profile.

I would recommend waiting on the developer for his fix unless you absolutely need it now. I really appreciate your work and I hope you have a great vacation. Perhapas this build process could also give you (the dev) insight into why the p
ublished version isn't working properly.

Documentation can be found here: https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

Note that some of it may be outdated, but it is mostly correct.

Cheers!

**Comment by FejZa** [comment] 2019-03-19 22:36
No, please do not do it this way. You don't need to package the extension to upload it to your Azure DevOps / Pipelines. Please just follow the steps descirbed in the README.md of the task you need. Every task has a README.md with the steps to upload the task.

As @milsoft described, it will work of course, but it's more complicated and it will create a new extension on the marketplace. Also you will not get updates if e.g. I update the extension on the marketplace.

**Comment by sudheesh001** [comment] 2019-03-21 12:50
Thank you @FejZa , This is incredible. However, a few things @Nirmalendu and I ran into was the Hosted Agents not allowing interactive inline powershell commands and disk space during installations of Unity.

As mentioned in https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/54#issuecomment-474370491 the process works perfectly except that if running on `Hosted` agents, it quickly runs into an error where there's not enough space on the disk. However, since the powershell command to install UnitySetup requires interaction with the command line, it might be an option to pass ` -Confirm:$false` along with the command followed by the installation of the editor and might be valuable to be documented in the future (ref #55).

```powershell
Install-Module -Name UnitySetup -AllowPrerelease -RequiredVersion 5.0.107-develop -Confirm:$false -Scope CurrentUser -Repository PSGallery -Force
```
Additionally a smaller command(s) if there's no explicit dependency which worked for us was
```powershell
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name UnitySetup -Confirm:$false -Scope CurrentUser -Force
```
Microsoft doesn't trust its own default repository and needs the user to explicitly grant permissions, however this can be set to be trusted before any module installations are done.

**Comment by AArnott** [comment] 2019-03-24 15:37
FYI for everyone: The Unity license serial number can be obtained from the Help->About box in the Unity desktop application.

**Comment by FejZa** [comment] 2019-05-06 11:31
I am going to close this issue since it hasn't occured anymore it seems and I am still not able to reproduce.

**Closed by FejZa** 2019-05-06 11:31 UTC
Labels: bug, question
