### ISSUE TITLE
Errors Finding the Editor Directory

### ISSUE THREAD

**Issue by adamhill** [Dinomite-Studios/unity-azure-pipelines-tasks#94] opened 2019-08-10 02:55 UTC
I am getting the following when he ActivateLicense step runs:

`
##[debug]unityEditorsPathMode=unityHub
##[debug]unityProjectPath=d:\a\1\s
##[debug]check path : C:\Program Files\Unity\Hub\Editor\2019.2.0f1
m_EditorVersionWithRevision\Editor
##[debug]task result: Failed
##[error]Error: Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2019.2.0f1
m_EditorVersionWithRevision\Editor
##[debug]Processed: ##vso[task.issue type=error;]Error: Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2019.2.0f1%0D%0Am_EditorVersionWithRevision\Editor
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2019.2.0f1%0D%0Am_EditorVersionWithRevision\Editor
##[section]Finishing: Unity Activate License
`

But the InstallEditor task runs successfully:
`
VERBOSE: Installing Windows Editor
VERBOSE: 08/10/2019 01:28:04: Installing Windows to C:\Program Files\Unity\Hub\Editor\2019.2.0f1.
VERBOSE: 08/10/2019 01:32:47: Succeeded.
VERBOSE: Installing Windows_IL2CPP
VERBOSE: 08/10/2019 01:32:47: Installing Windows_IL2CPP to C:\Program Files\Unity\Hub\Editor\2019.2.0f1.
VERBOSE: 08/10/2019 01:33:04: Succeeded.
##[debug]$LASTEXITCODE is not set.
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.151.2\powershell.ps1.
##[section]Finishing: Install Unity Editor
`

Any ideas? Is the period at the end of the path causing this? Is there anyway I can fix it if so?

Thanks.

REVISION: Manually specifying the directory in the License step gives the same error

**Comment by FejZa** [comment] 2019-08-11 07:28
Hi @adamhill, weird. I thought this issue was fixed by now. Going to have anothre look at it. The issue is this part `%0D%0Am_EditorVersionWithRevision`. It should not be there.

**Comment by FejZa** [comment] 2019-08-13 17:59
Hi @adamhill, I just released v2.5.2 of the extensions to the marketplace. Could you please make sure you updated to that version and run your pipeline again? Please make sure that the `debug` system variable is set to `true`, so we get better output.

If you have the latest versions, you should be seeing these versions used:
Unity Get Project Version: 1.0.4
Unity Activate License: 1.0.4

Thanks for the help!

**Comment by FejZa** [comment] 2019-08-16 11:27
I am closing this issue should be fixed with v1.0.4 of Unity Activate License Task

**Closed by FejZa** 2019-08-16 11:27 UTC
