### ISSUE TITLE
Project Version is reported wrongly - 2019.1.0.f2

### ISSUE THREAD

**Issue by eusebiu** [Dinomite-Studios/unity-azure-pipelines-tasks#77] opened 2019-04-22 12:14 UTC
The project version is wrongly reported in latest release:
##[debug]Processed: ##vso[task.complete result=Succeeded;]Found project version: 2019.1.0f2%0D%0Am_EditorVersionWithRevision

Reproduction steps:
1. Install the extension as described https://dinomite-studios.github.io/unity-azure-pipelines-tasks/
2. Create a Unity 2019.1.0f2 project.
3. Host it in Azure; create a build pipeline
4. Queue a build

Expected: successful build
Actual: Activation license fails since it cannot find the Editor.

**Comment by FejZa** [comment] 2019-04-22 12:17
Bummer, I fixed this in the Build and Get Project Version Task but did not in the Activation task. Thank you for reporting, I'll provide a fix soon!

**Comment by eusebiu** [comment] 2019-04-22 12:30
Thanks for coming back so fast!
Will these fixes be available in the Marketplace too?

**Comment by FejZa** [comment] 2019-04-22 12:36
Sure thing! I just released v2.4.2 to the Marketplace and it contains the fix for your issue:
https://marketplace.visualstudio.com/items?itemName=DinomiteStudios.64e90d50-a9c0-11e8-a356-d3eab7857116

Let me know if it solved the issue for you.

**Comment by eusebiu** [comment] 2019-04-23 07:52
Unfortunately, the issue is still there - do we need to update the extension manually or is automatically updated?

**Comment by StephenHodgson** [comment] 2019-04-23 15:15
Could also be this https://github.com/Microsoft/unitysetup.powershell/pull/171

**Comment by FejZa** [comment] 2019-04-23 15:36
Could be. @eusebiu could you provide me the exact log where the error occurs? The fix I did yesterday should have fixed this. Which task is failing for you? Is it Unity Build or Unity Activate License or Unity Get Project Version? Thanks a lot.

**Comment by eusebiu** [comment] 2019-04-23 19:52
The error has the root cause in the Unity Get Project Version - it returns the wrong value even if it succeeds.
`##[debug]Evaluating condition for step: 'Unity Get Project Version'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Unity Get Project Version
==============================================================================
Task         : Unity Get Project Version
Description  : Gets the project version of a Unity project.
Version      : 1.0.1
Author       : Dinomite Studios
Help         : Gets the project version of a Unity project. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[debug]agent.TempDirectory=d:\a\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_UNITYPROJECTPATH
##[debug]loaded 4
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : d:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.1\task.json
##[debug]adding resource file: d:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.1\task.json
##[debug]system.culture=en-US
##[debug]unityProjectPath=d:\a\1\s\App
##[debug]set projectVersion=2019.1.0f2
m_EditorVersionWithRevision
##[debug]Processed: ##vso[task.setvariable variable=projectVersion;issecret=false;]2019.1.0f2%0D%0Am_EditorVersionWithRevision
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Found project version: 2019.1.0f2%0D%0Am_EditorVersionWithRevision
##[section]Finishing: Unity Get Project Version`

Since this returns the wrong value, the license check fails:
`##[debug]Evaluating condition for step: 'Unity Get Project Version'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Unity Get Project Version
==============================================================================
Task         : Unity Get Project Version
Description  : Gets the project version of a Unity project.
Version      : 1.0.1
Author       : Dinomite Studios
Help         : Gets the project version of a Unity project. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[debug]agent.TempDirectory=d:\a\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_UNITYPROJECTPATH
##[debug]loaded 4
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : d:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.1\task.json
##[debug]adding resource file: d:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.1\task.json
##[debug]system.culture=en-US
##[debug]unityProjectPath=d:\a\1\s\App
##[debug]set projectVersion=2019.1.0f2
m_EditorVersionWithRevision
##[debug]Processed: ##vso[task.setvariable variable=projectVersion;issecret=false;]2019.1.0f2%0D%0Am_EditorVersionWithRevision
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Found project version: 2019.1.0f2%0D%0Am_EditorVersionWithRevision
##[section]Finishing: Unity Get Project Version`

The workaround I could find is to remove the line with m_EditorVersionWithRevision and leave only the line with the version.

**Comment by FejZa** [comment] 2019-04-29 18:41
Hi @eusebiu, I just did some more testing and could get the Project Version for Unity 2019.1.0f2 without any issues. You log indicates you already have v1.0.1 installed so I am really confused what's going on. Can I get some more info? Are you using a hosted agent or a custom one? What's your target platform?

**Comment by FejZa** [comment] 2019-04-29 18:42
I'd also like to find the cause of your build error related to IronPython. Do you think you can create a minified Unity Project for me to reproduce the issue?

**Comment by eusebiu** [comment] 2019-05-02 19:37
I am using a hosted agent; The target platform is Win64.
The IronPython is a separate issue which I guess that it comes from Unity since the normal Build works fine.

**Comment by christopheph** [comment] 2019-05-03 15:03
Dear, if I can give you a clue on the real issue behind that, the Get project task is adding "m_EditorVersionWithRevision" string after the path in the activate license task.

Thats why we get following error .

![image](https://user-images.githubusercontent.com/34710020/57146324-5abf9280-6dc5-11e9-95f5-542fac2e2ec2.png)

Can you fix it please and publish to the market place ?

Thanks a lot.

**Comment by christopheph** [comment] 2019-05-06 09:07
Hi,

Cloned the task, compiled and packaged myself and the task is working. I also applied some fix on the post activation task, like it has been for the other task. I created a pull request for this.

@FejZa it seems that there is something wrong on your build pipeline that compile your .ts in a wrong way.

Best regards,

**Comment by FejZa** [comment] 2019-05-06 11:30
Hi @christopheph thanks again for fixing this issue. I merged the PR and released the fix to the marketplace.

**Closed by FejZa** 2019-05-06 11:30 UTC
Labels: bug
